### ISSUE TITLE
setting BOOST_ROT to the root directory

### ISSUE THREAD

**Issue by babaz123** [HBadertscher/Matlab_BaslerCamDriver#11]
Hello,

Could you please help me set BOOST_ROT to the root directory?

Thank you

**Comment by HBadertscher** [comment]
First, you need to know, where Boost is installed. On my system, this is the path `C:\Program Files\Boost\boost_1_55_0`. 

Then, follow the steps described [here](https://kb.wisc.edu/cae/page.php?id=24500) to create a new environmental variable. Instead of the Variable name and value mentioned there, set the name to `BOOST_ROOT` and the value to the path where Boost is installed, e.g. `C:\Program Files\Boost\boost_1_55_0`.

Then the compilation should work.

**Comment by babaz123** [comment]
Thank you very much!

The compilation crashes now with the following errors:

>> make
=> Creating Libraries
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
=> Creating Functions
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
Error using mex
baslerGetParameter.cpp
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C2332: 'enum' : missing tag name
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C2236: unexpected 'class'
'ParamType'. Did you forget a ';'?
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C3381: 'ParamType' : assembly
access specifiers are only available in code compiled with a /clr option
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(14)
: error C4430: missing type specifier -
int assumed. Note: C++ does not support default-int
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(15)
: error C4430: missing type specifier -
int assumed. Note: C++ does not support default-int
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(16)
: error C4430: missing type specifier -
int assumed. Note: C++ does not support default-int
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(18)
: error C2143: syntax error : missing
';' before '}'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(18)
: error C4430: missing type specifier -
int assumed. Note: C++ does not support default-int
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(40)
: error C2039: 'Float' : is not a member
of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(40)
: error C2065: 'Float' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(41)
: error C2039: 'Int' : is not a member
of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(41)
: error C2065: 'Int' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(42)
: error C2039: 'Bool' : is not a member
of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(42)
: error C2065: 'Bool' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(43)
: error C2039: 'String' : is not a
member of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(43)
: error C2065: 'String' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(86)
: error C2450: switch expression of type
'ParamType' is illegal
        No user-defined-conversion operator available that can perform this
conversion, or the operator cannot be called
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2039: 'Float' : is not a member
of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2065: 'Float' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2051: case expression not
constant
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2039: 'Int' : is not a member
of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2065: 'Int' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2051: case expression not
constant
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2039: 'Bool' : is not a member
of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2065: 'Bool' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2051: case expression not
constant
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2039: 'String' : is not a
member of 'ParamType'

C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: see declaration of 'ParamType'
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2065: 'String' : undeclared
identifier
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2051: case expression not
constant
C:\Users\E31\Downloads\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(124)
: warning C4065: switch statement
contains 'default' but no 'case' labels



Error in make (line 63)
            mex(flags{:},ipaths,lpaths,libraryObjects{:},drivers{k})

>>

On 16 December 2015 at 03:04, Hannes Badertscher <notifications@github.com>
wrote:

> First, you need to know, where Boost is installed. On my system, this is
> the path C:\Program Files\Boost\boost_1_55_0.
>
> Then, follow the steps described here
> <https://kb.wisc.edu/cae/page.php?id=24500> to create a new environmental
> variable. Instead of the Variable name and value mentioned there, set the
> name to BOOST_ROOT and the value to the path where Boost is installed,
> e.g. C:\Program Files\Boost\boost_1_55_0.
>
> Then the compilation should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/11#issuecomment-165027205>
> .
>



-- 
M.E.

**Comment by babaz123** [comment]
Oops, I see this problem has already been reported here: https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/7

I'll try to follow what you suggested there.
