### ISSUE TITLE
Error compiling code with make.m

### ISSUE THREAD

**Issue by tomcastner** [HBadertscher/Matlab_BaslerCamDriver#13]
I get the following error when I try to run make.m file.

>> make
=> Creating Libraries
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
=> Creating Functions
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2013 Professional'.
Error using mex
baslerGetParameter.cpp
D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(39) : error C2039: 'map' : is not a member of 'std'
D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(39) : error C2065: 'map' : undeclared identifier
D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(39) : error C2275: 'std::string' : illegal use of this type as an expression
D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(39) : error C2065: 'paramMap' : undeclared identifier
D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(39) : error C2275: 'ParamType' : illegal use of this type as an expression
        D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(13) : see declaration of 'ParamType'
D:\Downloads\Matlab_BaslerCamDriver-master\Matlab_BaslerCamDriver-master\baslerGetParameter.cpp(86) : error C2065: 'paramMap' : undeclared identifier

Error in make (line 63)
            mex(flags{:},ipaths,lpaths,libraryObjects{:},drivers{k})

**Comment by Lansbergen** [comment]
Hi,

I came a cross a very similar (and unfortunately many more) error as you did. After some struggling I finally managed to create the mex-files by removing the type class in when stated enum class ParamType in line 13 of baslerGetParameter.cpp. It worked just fine for me.

Check out the tutorial I wrote on the topic.

https://github.com/Lansbergen/BaslerCamDriver_Installation_Tutorial_Windows_7.git

Let me know if it worked
