### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by ponagehl2** [HBadertscher/Matlab_BaslerCamDriver#23]
Hi,

I followed through the installation guide until the last compilation step. And it gave me the following error message:
fatal error C1083: Cannot open include file: 'pylon/PylonIncludes.h': No such file or directory

It seems to be missing a header file. I am wondering how I can resolve this issue.

Thanks,
Kevin

**Comment by HBadertscher** [comment]
Hi,

I assume you *have* installed Pylon? Have you used Pylon 4 or the newest Pylon 5?

Can you please run the following two commands in MATLAB, copy the resulting paths into the explorer and verify that both these folders exist and contain a couple of files or subfolders?

    fullfile(getenv('PYLON_ROOT'),'include')
    fullfile(getenv('PYLON_GENICAM_ROOT'),'library\CPP\include')

**Comment by ponagehl2** [comment]
Hi,

I am using Pylon 5 since I am trying to connect to Basler ac3800 14um camera, which I believe is a newer model and can only be recognized using the newer version of Pylon.

The commands you provided above indicate that the Pylon root folder is for Pylon 4. Is there a way to modify this?

Appreciate the help,
Kevin

**Comment by HBadertscher** [comment]
Okay, thanks for the feedback. So, you can change these paths to point to the right place from within MATLAB. The important thing is to find the correct places: 

- For `PYLON_ROOT`, this is something like `C:\Programs\Pylon 5\` or wherever Pylon 5 is installed. Please check that this folder has an `includes` subfolder.
- The `PYLON_GENICAM_ROOT` is usually a subfolder of that, something like `genicam`. You know that you have the right place, when you have the subfolders `library\CPP\include`. 

Setting an environment variable is then as simple as

    setenv('PYLON_ROOT', 'C:\the\path\you\found')
    setenv('PYLON_GENICAM_ROOT', 'C:\the\other\path')

You have to call these functions before running `make.m` (or simply copy them to the beginning of `make.m`.

I hope that this solves these errors. However, I fear that you might run into other problems as reported [here](https://github.com/HBadertscher/Matlab_BaslerCamDriver/issues/22), as I have developed this driver for Pylon 4 and haven't been able to port it to Pylon 5.

**Comment by ntb13230** [comment]
Hello, 

I've found your files and I'm trying to use them with my Basler acA1920-25um camera. Following the fact that you have developed this for pylon4 that's what I've installed and also I got boost 1.55 After a while of struggling I got to the point where your make.m file finally finds pylon files properly, however i think there is a problem with the boost. 

First of all in your make file , in libraries paths, the boost one has addition of 'stage\lib', but there is no such a path in this folder. I tried to change it for 'libs' but this fails as well. Where should this point to?

what i'm getting now while running the make file is this (sorry - very long): 

>> make
=> Creating Libraries
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
=> Creating Functions
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
MEX completed successfully.
Building with 'Microsoft Windows SDK 7.1 (C++)'.
Error using mex
baslerGetParameter.cpp
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C2332: 'enum' : missing tag name
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C2236: unexpected 'class' 'ParamType'. Did you forget a ';'?
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
: error C3381: 'ParamType' : assembly access specifiers are only available in code compiled
with a /clr option
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(14)
: error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(15)
: error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(16)
: error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(18)
: error C2143: syntax error : missing ';' before '}'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(18)
: error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(40)
: error C2039: 'Float' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(40)
: error C2065: 'Float' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(41)
: error C2039: 'Int' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(41)
: error C2065: 'Int' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(42)
: error C2039: 'Bool' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(42)
: error C2065: 'Bool' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(43)
: error C2039: 'String' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(43)
: error C2065: 'String' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(86)
: error C2450: switch expression of type 'ParamType' is illegal
        No user-defined-conversion operator available that can perform this conversion, or the
        operator cannot be called
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2039: 'Float' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2065: 'Float' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(88)
: error C2051: case expression not constant
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2039: 'Int' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2065: 'Int' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(95)
: error C2051: case expression not constant
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2039: 'Bool' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2065: 'Bool' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(104)
: error C2051: case expression not constant
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2039: 'String' : is not a member of 'ParamType'
        C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(13)
        : see declaration of 'ParamType'
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2065: 'String' : undeclared identifier
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(111)
: error C2051: case expression not constant
C:\Users\ntb13230\Documents\MATLAB\Cameras\HBadertscher-Matlab_BaslerCamDriver-419332a\baslerGetParameter.cpp(124)
: warning C4065: switch statement contains 'default' but no 'case' labels
Error in make (line 64)
            mex(flags{:},ipaths,lpaths,libraryObjects{:},drivers{k})

I don't know if that's something I'm doing wrong or... could you please have a look?
(btw - I'm using Matlab 2015a, 64 bit)

Thank you!
