### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mihaig66** [HBadertscher/Matlab_BaslerCamDriver#25]
Hi,

I am having some problems compiling, I get this error: 
Error using mex
LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc100-mt-1_62.lib'

I am using pylon 4 and Windows 7 .

Do you have any idea what can be the problem here? 

Many thanks,
Mihai

**Comment by HBadertscher** [comment]
Hi, it says it can't find the Boost library. Have you compiled them manually, or did you use pre-compiled libraries as suggested in [this tutorial](https://github.com/Lansbergen/BaslerCamDriver_Installation_Tutorial_Windows_7)? If you follow the tutorial closely, it should work.

**Comment by mihaig66** [comment]
In the end I have managed to solve the problem, it was indeed a problem with the Boost library :)

Offtopic: I am barely getting a framerate of 2 fps, any idea of what can be the problem...
