### ISSUE TITLE
Pylon 4 x64

### ISSUE THREAD

**Issue by AnsusBega** [HBadertscher/Matlab_BaslerCamDriver#31]
Hi! thank you for your contribution.

Do you happen to have pylon x64 version 4?
Currently, only version 5 is available on Basler download page.

All the best,
Bega

**Comment by HBadertscher** [comment]
Hi, sorry I'm afraid I won't be able to help you out with that.

On the Basler website, it says:

> You’re interested in older pylon versions? Please contact our Support Team.

Personally, I had very good experience in dealing with the Basler support and their official sales partner. I'm sure they'll be happy to send you the right version.

One more thought: the camera support of MATLAB has improved significantly over the past months / years. Have you tried the Image Acquisition toolbox?
